### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by softwarespot** [jpederson/Squirrel.js#28]
I was thinking today about adding an option to specify a callback when data is stored to the local/sessionStorage. I then came across [this](https://github.com/jpederson/Squirrel.js/pull/1) in which it was outlined that perhaps this would be a good idea. What do people think?

**Comment by jpederson** [comment]
I haven't had a need for it, but don't see any harm in having a callback that we pass the data (field name and value) into so that devs can do whatever they want with each (or one particular field) whenever they're stored. The problem, is most often, they're updated on keyup, so it could certainly get heavy if a developer is using a large callback function for every single time a value updates. Nevertheless, it could be useful to someone I suppose. I just can't really think of a use case that wouldn't be taken care of by `$('.squirrel input').on('keyup');`..

**Comment by softwarespot** [comment]
Nah good point. Dumb idea now I think about ( posted late last night =) ) Your suggestion is pretty obvious, why wouldn't someone do that?! =D
