### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by michelemarrionline** [jpederson/Squirrel.js#3]
that's not an issue but a request.. ;)

can u make this one work if a page is accidentally closed? maybe with cookies?

thanks in advance.

mike

**Comment by jpederson** [comment]
I intentionally didn't build it to use localStorage because in some circumstances it could be a security concern - just as an example, imagine it in a loan application that someone is filling out on a library computer - they close the browser, but all their private information doesn't get cleared.

That said, I've added support for localStorage as a configuration option (https://github.com/jpederson/Squirrel.js/commit/28f84e65a5cdff5b7feb954d4516e9de455b7ac3). To switch the plugin to use localStorage, instantiate like this (you'll have to use a new class on your form):

``` js
// the storage_method option takes either 'local' or 'session' and defaults to 'session'.
$('.squirrel-persistent').squirrel( 'init', {
  storage_method: 'local'
});
```

Let me know how this works for you when you update to the new version! And be careful with where you use it, hah..

Best,
James

**Comment by jpederson** [comment]
Hi Mike,

Hoping you get the chance to try this out soon - let me know how it works out for you - but I've tested already so if I don't hear back in a week or so I'll mark this feature request completed.

Thanks for contributing!

James

**Comment by michelemarrionline** [comment]
Yea, all working perfectly ;)

**Comment by jpederson** [comment]
Glad to hear - have a good one!
